name = "Art du Desir"
license = "MIT"
licenselink = ""
description = "Theme pour L'Art du Desir par 1969"
tags = ["blog", "seo"]
features = ["blog"]
min_version = "0.100.0"

[author]
  name = "1969"
  homepage = "https://1969.fr"
